# A sample Gemfile
source "https://rubygems.org"
gem "compass", ">=0.12.2"
gem "sassy-buttons", ">=0.1.4"
gem "survivalkit", ">=1.0.beta.8"
gem "breakpoint", ">=1"
gem "susy", ">=1"
gem "compass-recipes"
