<div class="abaproduct-content">
  <div class="abaproduct-image">
    <a href="http://images.indiebound.com/361/487/9781594487361.jpg" title="This Is How You Lose Her" class="thickbox initThickbox-processed" rel="field_image_cache_0">
      <img src="http://images.booksense.com/images/books/361/487/FC9781594487361.JPG" title="" onerror="this.src = '/sites/all/modules/custom/aba_product/book_not_found.jpg';"></a>
    <div id="google-book-preview">
      <script type="text/javascript" src="http://books.google.com/books/previewlib.js"></script>
      <script type="text/javascript">
        GBS_insertPreviewButtonPopup('ISBN:9781594487361');
        GBS_setViewerOptions({'showLinkChrome': false});
        </script>
      <span id="__GBS_Button0"></span>
    </div>
  </div>
  <div class="abaproduct-page">
    <div class="abaproduct-title">
      <h2>This Is How You Lose Her              (Hardcover)</h2>
    </div>
    <div class="abaproduct-authors">
      By
      <a href="/search/apachesolr_search/?author_filter=Diaz%2C+Junot">Junot Diaz</a>
    </div>
    <div class="abaproduct-page-details">
      <div class="abaproduct-price">$26.95</div>
    </div>
    <div class="abaproduct-cart">
      <fieldset class="availability">
        On hand as of Sep 23 4:05am (FICTION)
        <br></fieldset>
      <div class="add-to-cart">
        <form action="/book/9781594487361" accept-charset="UTF-8" method="post" id="uc-product-add-to-cart-form-49764-1">
          <div>
            <input type="hidden" name="qty" id="edit-qty-1" value="1">
            <input type="submit" name="op" id="edit-submit-49764" value="Add to cart" class="form-submit node-add-to-cart">
            <input type="hidden" name="form_build_id" id="form-28fd28e730b16dcbafda3441d08f4daf" value="form-28fd28e730b16dcbafda3441d08f4daf">
            <input type="hidden" name="form_id" id="edit-uc-product-add-to-cart-form-49764-1" value="uc_product_add_to_cart_form_49764"></div>
        </form>
      </div>
      <!-- <div class="abaproduct-special">for LSI/ebook downloads/others</div>
    -->
    <div class="abaproduct-status">On Our Shelves Now</div>
  </div>

  <div class="abaproduct-related-editions">
    <table>
      <tbody>
        <tr>
          <td>

            <div class="abaproduct-related-editions-head">Related Editions</div>
            <div class="item-list">
              <ul>
                <li class="first">
                  <a href="/gbook/v/xyG9uXBd_zgC">Google eBook (9/2012): $12.99</a>
                </li>
                <li>
                  <a href="/book/v/9781594487361">Hardcover (8/2012): $26.95</a>
                </li>
                <li class="last">
                  <a href="/book/v/9781611761108">Compact Disc (8/2012): $29.95</a>
                </li>
              </ul>
            </div>
            <div class="abaproduct-related-editions-list">
              <a href="#relatededition">More...</a>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

</div>
</div>
